# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='constraint',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
