# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161105_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
