# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170416_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='zerofill',
            field=models.BooleanField(default=False),
        ),
    ]
