# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161106_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='field',
            name='primary',
        ),
    ]
