# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 21:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161110_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 10, 21, 58, 58, 759804, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='table',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app.Table'),
            preserve_default=False,
        ),
    ]
