# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161206_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='type_table',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
