# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campo', to='app.Field'),
        ),
    ]
