# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170228_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='chave',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chave', to='app.Field'),
            preserve_default=False,
        ),
    ]
