# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_restricao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo_Tabela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_campo', models.CharField(choices=[('PK', 'Chave Primária'), ('FK', 'Chave Estrangeira'), ('Normal', 'Campo Normal')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='restricao',
            name='campo',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='tabela',
        ),
        migrations.DeleteModel(
            name='Restricao',
        ),
        migrations.AddField(
            model_name='campo_tabela',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Campo'),
        ),
        migrations.AddField(
            model_name='campo_tabela',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tabela'),
        ),
    ]
