# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_grupo_grupo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_usuario',
            name='situacao',
            field=models.CharField(choices=[('OK', 'Membro'), ('Pendente', 'Pendente')], default='pendente', max_length=10),
        ),
    ]
