# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_usuario_ultimo_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='tipo_campo_bd',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
