# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_campo_tipo_campo_bd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo_campo_bd',
            field=models.CharField(default='', max_length=20),
        ),
    ]
