# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20170413_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo_campo_bd',
            field=models.CharField(max_length=20),
        ),
    ]
