# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('tipo_atributo', models.CharField(default=None, max_length=20)),
                ('tamanho_itens', models.CharField(default=None, max_length=10)),
                ('unsigned', models.BooleanField(default=False)),
                ('null', models.BooleanField(default=False)),
                ('zerofill', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Campo_Tabela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_campo', models.CharField(choices=[('PK', 'Chave Primária'), ('FK', 'Chave Estrangeira'), ('Normal', 'Campo Normal')], max_length=20)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Campo')),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campo', to='app.Campo')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependente', to='app.Campo')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('OK', 'Membro'), ('Pendente', 'Pendente')], default='pendente', max_length=10)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('forma_normal', models.PositiveSmallIntegerField(default=0)),
                ('tabela_tipo', models.PositiveSmallIntegerField(default=1)),
                ('renomear', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=64)),
                ('ultima_hash', models.CharField(max_length=64)),
                ('ultimo_login', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='grupo_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='documento',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo'),
        ),
        migrations.AddField(
            model_name='campo_tabela',
            name='tabela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tabela'),
        ),
    ]
