# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161110_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='normal_form',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
