# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_table_normal_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Table'),
        ),
    ]
