# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170228_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveEstrangeira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Field')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Table')),
            ],
        ),
    ]
