# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-11 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_chaveestrangeira'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Documento',
        ),
    ]
