# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20170315_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='renomear',
            field=models.BooleanField(default=True),
        ),
    ]
