# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_tabela_renomear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabela',
            name='renomear',
            field=models.BooleanField(default=False),
        ),
    ]
