# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
