# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_grupo_usuario_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Grupo'),
            preserve_default=False,
        ),
    ]
