# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_usuario_ultimo_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='null',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campo',
            name='tamanho_itens',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='tipo_atributo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='unsigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campo',
            name='zerofill',
            field=models.BooleanField(default=False),
        ),
    ]
