# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20170416_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo_atributo',
            field=models.CharField(default='INT', max_length=20),
        ),
    ]
