# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20170429_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultima_hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_login',
            field=models.DateTimeField(null=True),
        ),
    ]
