# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20170505_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ultima_hash',
            new_name='sessao_hash',
        ),
    ]
