# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-13 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20170512_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado_exemplo',
            old_name='text',
            new_name='texto',
        ),
    ]
